//kumpulan kata-kata agar penangkapan oleh SpeechRecognition kata lebih presisi
const words: string[] = [
    "aku",
    "masih",
    "teka",
    "javascript",
    "golang",
    "rust",
    "tuliskan",
    "tolong",
    "kodingan",
    "code",
    "hello",
    "world",
    "kucing",
    "sayang",
    "makan",
    "batu",
    "senang",
    "okelah",
    "mamang",
    "alterra",
    "academy",
    "freya",
    "jekate48",
    "meong",
    "monyet",
    "kambing",
    "christiano",
    "ronaldo",
    "messi",
    "mbappe",
];

export default words;
